.TH Laminax-LOOKING-GLASS 1 2013-03-08  Laminax "Laminax manual"
.SH NAME
Laminax-looking-glass \- Debugging interface for Laminax
.SH SYNOPSIS
.SY Laminax-looking-glass
.SH DESCRIPTION
.LP
.B Laminax-looking-glass
runs the graphical debugger interface for Laminax.
.SH AUTHOR
.B Laminax-looking-glass
is written by the Mint project <root@linuxmint.com>.
.P
This manual page was written by Nicolas Bourdaud
<nicolas.bourdaud@gmail.com> for the Debian project.
.SH "SEE ALSO"
.BR Laminax (1)
