.TH Laminax-SCREENSAVER-LOCK-DIALOG 1 2013-03-08  Laminax "Laminax manual"
.SH NAME
Laminax-screensaver-lock-dialog \- message setting for Laminax screensaver
.SH SYNOPSIS
.SY Laminax-screensaver-lock-dialog
.SH DESCRIPTION
.LP
.B Laminax-screensaver-lock-dialog
runs the graphical interface to set an away message when executing
Laminax-screensaver.
.SH NOTE
This dialog applet will work only if
.B Laminax-screensaver
is installed. Therefore, Laminax desktop will call the dialog only if the
latter is effectively installed.
.SH AUTHOR
.B Laminax-screensaver-lock-dialog
is written by the Mint project <root@linuxmint.com>.
.P
This manual page was written by Nicolas Bourdaud
<nicolas.bourdaud@gmail.com> for the Debian project.
.SH "SEE ALSO"
.BR gnome-screensaver-command (1)
