.TH Laminax-MENU-EDITOR 1 2012-07-23  Laminax "Laminax manual"
.SH NAME
Laminax-menu-editor \- Editor for the panel menu
.SH SYNOPSIS
.SY Laminax-menu-editor
.SH DESCRIPTION
.LP
\fBLaminax-menu-editor\fP runs the graphical user interface allowing to
edit the menu displayed in Laminax.
.SH "SEE ALSO"
.BR Laminax-settings (1)

