.TH Laminax-LAUNCHER 1 2012-07-29  Laminax "Laminax manual"
.SH NAME
Laminax-launcher \- Start or restart a Laminax session
.SH SYNOPSIS
.SY Laminax-launcher
.SH DESCRIPTION
.LP
\fBLaminax-launcher\fP runs the graphical user interface allowing to
start or restart a session of Laminax desktop.
.SH "SEE ALSO"
.BR Laminax (1)

